# -*- mode: yaml-*-
# vi: set ft=yaml sw=2 ts=2 :

- name: Configure development machine
  hosts: all
  sudo: True
  tasks:
    - name: set locale
      lineinfile: dest=/etc/default/locale line="LC_ALL=C"

    - name: install curl
      apt: name={{ item }} update_cache=yes
      with_items:
        - curl
        - postgresql 
        - postgresql-contrib
        - libpq-dev
        - python-dev

    - name: install pip
      shell: curl https://bootstrap.pypa.io/get-pip.py | python -

    - pip: name=virtualenv

    - pip: requirements=/project/requirements.pip virtualenv=~/ENV

    - name: add node ppa
      shell: curl -sL https://deb.nodesource.com/setup | bash -

    - name: install node and npm
      apt: name=nodejs update_cache=yes

    - name: install node dependencies
      npm: name=bower global=yes 

    - name: install node dependencies
      npm: name=grunt-cli global=yes 

    - name: install node dependencies
      npm: path=/project
